name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run test
      run: ./gradlew test
    - name: Android Emulator
      # You may pin to the exact commit or the version.
      # uses: vgaidarji/android-github-actions-emulator@30c50f42518922e01004c2152911bb458d33ff3b
      uses: vgaidarji/android-github-actions-emulator@v1.0.1
